reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:create]
  end
  resources :posts

end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  # belongs_to :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'User'

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub


end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :Post

  belongs_to :sub,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :Sub
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  # has_many :posts

  has_many :sub_posts,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: "PostSub",
    inverse_of: :sub

  has_many :posts,
    through: :sub_posts,
    source: :post



end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "Sub"

  has_many :posts,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Post'

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_cred(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_login

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

reddit_clone/app/controllers/post_subs_controller.rb
class PostSubsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_ids = [params[:sub_id]]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @subs = Sub.all
      render :new
    end
  end

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    render :edit
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post && @post.update(post_params)
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = ["Invalid params"]
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    username = params[:user][:username]
    password = params[:user][:password]
    @user = User.find_by_cred(username, password)
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Invalid params for update"]
      render :edit
    end
  end

  private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end

end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/post_subs_helper.rb
module PostSubsHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <% if logged_in? %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

  <% flash[:errors].try(:each) do |error| %>
    <%= error %>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/post_subs/create.html.erb
<h1>PostSubs#create</h1>
<p>Find me in app/views/post_subs/create.html.erb</p>

reddit_clone/app/views/post_subs/destroy.html.erb
<h1>PostSubs#destroy</h1>
<p>Find me in app/views/post_subs/destroy.html.erb</p>

reddit_clone/app/views/post_subs/edit.html.erb
<h1>PostSubs#edit</h1>
<p>Find me in app/views/post_subs/edit.html.erb</p>

reddit_clone/app/views/post_subs/index.html.erb
<h1>PostSubs#index</h1>
<p>Find me in app/views/post_subs/index.html.erb</p>

reddit_clone/app/views/post_subs/new.html.erb
<h1>PostSubs#new</h1>
<p>Find me in app/views/post_subs/new.html.erb</p>

reddit_clone/app/views/post_subs/show.html.erb
<h1>PostSubs#show</h1>
<p>Find me in app/views/post_subs/show.html.erb</p>

reddit_clone/app/views/post_subs/update.html.erb
<h1>PostSubs#update</h1>
<p>Find me in app/views/post_subs/update.html.erb</p>

reddit_clone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

reddit_clone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<form action="<%= post_url(@post) %>" method="post">

  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="" value="Update Post">

</form>

reddit_clone/app/views/posts/new.html.erb
<h1>New Post</h1>
<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>
  <br>


  <input type="hidden" name="post[sub_ids][]" value="">

  <% @subs.each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
        />
    </label>
      <br>
  <% end %>



  <input type="submit" name="" value="Create Post">

</form>

reddit_clone/app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>
<ul>
  <li><%= @post.url %></li>
  <li><%= @post.content %></li>
</ul>

reddit_clone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

reddit_clone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form action="<%= sub_url(@sub) %>" method="post">

  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Update Sub">

</form>

reddit_clone/app/views/subs/index.html.erb
<%= link_to "New Sub", new_sub_url %>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %>
<% end %>

<%= link_to "New Post", new_post_url %>

reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>
<form action="<%= subs_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Create Sub">

</form>

reddit_clone/app/views/subs/show.html.erb
<h3>Moderator: </h3>
<%= @sub.moderator.username %>

<h5>Title: </h5>
<%= @sub.title %>

<h5>Description</h5>
<%= @sub.description %>
<br>
<br>
<br>
<%= link_to "Edit Sub", edit_sub_url(@sub) %>
<%= link_to "Subs", subs_url %>

<h2>Posts</h2>
  <% @sub.posts.each do |post| %>
    <%= post.title %>
    <%= post.url %>
    <%= post.content %>
    <br>
  <% end %>

<h3>Add Post</h3>
<form class="" action="<%= sub_posts_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>
    URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>
    Content
    <input type="text" name="post[content]" value="">
  </label>

  <input type="submit" name="" value="Add Post">

</form>

reddit_clone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

reddit_clone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

reddit_clone/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

reddit_clone/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

reddit_clone/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">

</form>

reddit_clone/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

reddit_clone/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>